### ISSUE TITLE
Implementation of LCOM2 and LCOM3

### ISSUE THREAD

**Issue by ssousaleo** [diegocedrim/organic#12]
**LCOM -> Lack Of Cohesion Of Methods**

Definitions used for LCOM2 and LCOM3

- m = number of procedures (methods) in class
- a = number of variables (attributes) in class
- mA = number of methods that access a variable (attribute)
- sum(mA) = sum of mA over attributes of a class

LCOM2 = 1 - sum(mA)/(m*a)
LCOM3 = (m - sum(mA)/a) / (m-1)

The metric definition as well as its implementation are available at:
[Cohesion metrics](http://www.aivosto.com/project/help/pm-oo-cohesion.html)
[Design metrics](http://www.cs.sjsu.edu/~pearce/cs251b/DesignMetrics.htm)

**Comment by diegocedrim** [comment]
Solved by this [commit](https://github.com/diegocedrim/organic/commit/bc01a05ce5d1f9e1eba6bd86447d9970ef0c0e8a)
