### ISSUE TITLE
Syntactical Agglomeration Detector

### ISSUE THREAD

**Issue by diegocedrim** [diegocedrim/organic#3]
We must implement the syntactic agglomeration detector algorithm.  This kind of agglomeration can be inter-component or intra-component. According to the author of the paper, the definition of these terms are:

> We classify the syntactic agglomerations according to their scope in the program: (i) intra-component agglomerations, i.e. those entirely located within a single component, and (ii) inter-component agglomerations, i.e. those located in two or more agglomeration. The intra-component algorithm searches for code elements in the same component that are syntactically related. The different between the inter-component and intra-component algorithm (described in the paper) relies on the scope that limits the search for anomalous code elements. The inter-component algorithm searches for related code elements that involve two or more design components, while the intra-component algorithm searches for code elements inside of one only component. The algorithm to identify intra-component agglomerations is shown below.

``` java
public List{} getIntraAgglomeration(Set dc, int agglomThreshold){
    IntraAgglomerations = {}
    anomalousElems = {}

    for(each design component dc in the program){
        anomalousElems.addAll(getAnomalousElemsOfComponent(dc))
    }

    //Adding anomalous code elements as vertices in the graph
    graphIntraElems = new graphIntraElems().addVertex.addAll(anomalousElems) 

    for(each e1 in anomalousElems){
        for(each e2 in anomalousElems){ 
            //Creating the Intra-component graph 
            if(isRelated(e1,e2) && (e1.getDesignComponent() == e2.getDesignComponent())){
                graphIntraElems.addEdge(e1,e2)
            }
        }
    }

    // Adding the connected components as agglomerations          
    IntraAgg = new IntraAgg().addAll(getConnectedComponents(graphIntraElems))

    // Selecting only agglomerations above the predefined threshold
    for(each a in IntraAgg){
        if(size(a.getAnomalies()) > agglomThreshold){
            IntraAgglomerations.add(a)
        }
    }
    return IntraAgglomerations
 }
```

**Comment by diegocedrim** [comment]
@ssousaleo, I'm implementing the syntactical checkers to generate the edges of the so-called Smelly Graph. 

In the paper, you say that: "An explicit relationship is established between two anomalous elements when they have at least one of the following dependencies: shared attribute, method call, class extension or method overload."

The **Shared attribute** condition is evident.

**Method call**: If _a_ calls _b_, I should create an edge between _a_ and _b_ in the graph. Since the graph is undirected, I'm also creating an edge between _b_ and _a_. Is that right? Or this graph should be directed?

**Class extension**: Suppose that A extends B and B extends C. A and C are smelly. Should I create an edge between A and C?

**Comment by ssousaleo** [comment]
@diegocedrim Yes, you should. A and C classes are syntactically related because of the transition relation (a->b, b->c, then a->c). As both classes (A and C) are smelly, there is a edge between A and C.
